//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLySpare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class danhsachlinhkien
    {
        public int id { get; set; }
        public string model { get; set; }
        public string tenlinhkien { get; set; }
        public string malinhkien { get; set; }
        public string maker { get; set; }
        public string donvi { get; set; }
        public Nullable<int> dongia { get; set; }
        public Nullable<int> tonkho { get; set; }
        public string ghichu { get; set; }
    }
}
